-- Script generated by Redgate Compare v1.19.5.12868
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.persons...';END$$;
DROP TABLE public.persons;

SET check_function_bodies = true;
