-- Script generated by Redgate Compare v1.19.5.12868
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.persons...';END$$;
CREATE TABLE public.persons (
    personid integer,
    lastname character varying(255),
    firstname character varying(255),
    address character varying(255),
    city character varying(255),
    state character varying(300)
);
ALTER TABLE public.persons OWNER TO pgmain;

SET check_function_bodies = true;
